language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo test --verbose --features serde
  - cargo doc --no-deps --features serde
  - cargo fmt --all -- --check